-- +goose Up
CREATE TABLE feeds (
  ID UUID PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  url TEXT NOT NULL,
  name TEXT NOT NULL,
  user_ID UUID NOT NULL REFERENCES users(ID) ON DELETE CASCADE
);

--+goose Down
DROP TABLE feeds;